[wokwi]
version = 1
elf = ".pio/build/esp32dev/firmware.elf"
firmware = ".pio/build/esp32dev/firmware.bin"

# Cấu hình WiFi cho simulation
[[net.forward]]
from = "localhost:3636" 
to = "target:80"             

# Serial Monitor
[serial]
monitor = true